'use strict';
const fs=require('node:fs');
const fsp=fs.promises;
const path=require('node:path');
const crypto=require('node:crypto');
const {atomicWrite}=require('./store.cjs');
const MAX_FILE=4*1024*1024;
const EXCLUDED=new Set(['.git','node_modules','.venv','venv','__pycache__','dist','build','.next','.dart_tool','coverage','.idea','.vscode']);
const revision=content=>crypto.createHash('sha256').update(content).digest('hex');
const language=filename=>({'.js':'javascript','.cjs':'javascript','.mjs':'javascript','.jsx':'javascript','.ts':'typescript','.tsx':'typescript','.json':'json','.py':'python','.html':'html','.css':'css','.md':'markdown','.yaml':'yaml','.yml':'yaml','.xml':'xml','.cs':'csharp','.rs':'rust','.go':'go','.sh':'shell','.ps1':'powershell','.sql':'sql','.dart':'dart','.txt':'plaintext'}[path.extname(filename).toLowerCase()]||'plaintext');
function contained(root,target){const relative=path.relative(root,target);return relative==='' || (!relative.startsWith(`..${path.sep}`)&&relative!=='..'&&!path.isAbsolute(relative));}
class Workspace {
  constructor(store,options={}){this.store=store;this.chooseFolder=options.chooseFolder;this.trashPath=options.trashPath;this.emit=options.emit||(()=>{});this.watcher=null;}
  root(){const value=this.store.state.currentWorkspace;if(!value)throw new Error('Open a workspace folder first.');if(!fs.existsSync(value))throw new Error('The selected workspace no longer exists. Open another folder.');const real=fs.realpathSync(value);if(real!==value)throw new Error('The workspace location changed. Reopen the canonical folder.');return real;}
  resolve(input,allowRoot=false){
    const root=this.root();if(typeof input!=='string'||input.includes('\0')||(!input&& !allowRoot))throw new Error('A relative workspace path is required.');
    if(path.isAbsolute(input))throw new Error('Use a relative path inside the selected workspace.');
    const target=path.resolve(root,input||'.');if(!contained(root,target)||(!allowRoot&&target===root))throw new Error('The path escapes the selected workspace.');
    let ancestor=target;while(!fs.existsSync(ancestor)){const parent=path.dirname(ancestor);if(parent===ancestor)throw new Error('The parent folder is unavailable.');ancestor=parent;}
    if(!contained(root,fs.realpathSync(ancestor)))throw new Error('A symbolic link points outside the selected workspace.');
    if(fs.existsSync(target)&&!contained(root,fs.realpathSync(target)))throw new Error('A symbolic link points outside the selected workspace.');
    // .git mutations belong to Git itself, never editor writes.
    if(path.relative(root,target).split(path.sep).includes('.git'))throw new Error('Git internal files cannot be edited through AuraScript.');
    return target;
  }
  rel(target){return path.relative(this.root(),target).split(path.sep).join('/');}
  async open(payload={}){
    let selected=payload.path;if(!selected){if(!this.chooseFolder)throw new Error('Folder selection is unavailable.');selected=await this.chooseFolder();}if(!selected)return {cancelled:true};
    const root=await fsp.realpath(selected);if(!(await fsp.stat(root)).isDirectory())throw new Error('Choose a directory for the workspace.');
    const item={path:root,name:path.basename(root),lastOpenedAt:new Date().toISOString()};this.store.state.currentWorkspace=root;this.store.state.workspaces=[item,...this.store.state.workspaces.filter(w=>w.path!==root)].slice(0,20);this.store.save();this.watch(root);this.emit({type:'workspace:changed',root});return {root,workspace:item,...await this.list({})};
  }
  watch(root){if(this.watcher)this.watcher.close();try{let timer;this.watcher=fs.watch(root,{recursive:true},(_event,filename)=>{if(filename&&String(filename).split(/[\\/]/).some(p=>EXCLUDED.has(p)))return;clearTimeout(timer);timer=setTimeout(()=>this.emit({type:'workspace:changed',root,path:filename?.toString()||''}),180);timer.unref?.();});this.watcher.on('error',()=>{});}catch{/* File operations emit changes even on platforms without recursive watching. */}}
  async list(payload={}){const target=this.resolve(payload.path||'',true);const entries=[];for(const entry of await fsp.readdir(target,{withFileTypes:true})){if(EXCLUDED.has(entry.name))continue;const filename=path.join(target,entry.name);let stat;try{this.resolve(this.rel(filename));stat=await fsp.stat(filename);}catch{continue;}entries.push({name:entry.name,path:this.rel(filename),kind:stat.isDirectory()?'directory':'file',size:stat.size,symbolicLink:entry.isSymbolicLink()});}entries.sort((a,b)=>(a.kind===b.kind?0:a.kind==='directory'?-1:1)||a.name.localeCompare(b.name));return {root:this.root(),path:this.rel(target),entries};}
  async read(payload){const target=this.resolve(payload.path);const stat=await fsp.stat(target);if(!stat.isFile())throw new Error('Select a text file.');if(stat.size>MAX_FILE)throw new Error('Files larger than 4 MB cannot be opened in the editor.');const bytes=await fsp.readFile(target);if(bytes.includes(0))throw new Error('Binary files cannot be opened as text.');const content=bytes.toString('utf8');return {path:this.rel(target),name:path.basename(target),content,revision:revision(bytes),language:language(target)};}
  async create(payload){const target=this.resolve(payload.path);if(fs.existsSync(target))throw new Error('A file or folder already exists at this location.');if(!fs.existsSync(path.dirname(target)))throw new Error('The parent directory does not exist.');if(payload.kind==='directory')await fsp.mkdir(target);else if(payload.kind==='file')await fsp.writeFile(target,'',{flag:'wx'});else throw new Error('Choose file or directory.');this.changed(payload.path);return payload.kind==='file'?this.read(payload):{path:this.rel(target),kind:'directory'};}
  async save(payload){if(typeof payload.content!=='string'||Buffer.byteLength(payload.content)>MAX_FILE)throw new Error('File content must be text smaller than 4 MB.');const target=this.resolve(payload.path);if(fs.existsSync(target)){const current=await this.read(payload);if(!payload.revision||payload.revision!==current.revision)throw new Error('The file changed on disk. Reload and compare before saving.');}else{if(payload.revision)throw new Error('The file was removed on disk. Recreate it explicitly.');if(!fs.existsSync(path.dirname(target)))throw new Error('The parent directory does not exist.');}atomicWrite(target,payload.content);this.changed(payload.path);return this.read(payload);}
  async rename(payload){const original=this.resolve(payload.path),target=this.resolve(payload.newPath);if(!fs.existsSync(original))throw new Error('The original file or folder does not exist.');if(fs.existsSync(target))throw new Error('The destination already exists.');if(contained(original,target))throw new Error('A folder cannot be moved inside itself.');if(!fs.existsSync(path.dirname(target)))throw new Error('The destination parent does not exist.');await fsp.rename(original,target);this.changed(payload.newPath);return {path:this.rel(target)};}
  async trash(payload){const original=this.resolve(payload.path);if(!fs.existsSync(original))throw new Error('The selected item does not exist.');const id=crypto.randomUUID(),retained=path.join(this.store.directory,'trash',id);await fsp.mkdir(path.dirname(retained),{recursive:true});await fsp.cp(original,retained,{recursive:true,dereference:false,errorOnExist:true,force:false});await fsp.rm(original,{recursive:true});const item={id,path:this.rel(original),root:this.root(),name:path.basename(original),deletedAt:new Date().toISOString(),retained};this.store.state.trash.unshift(item);this.store.save();this.changed(item.path);return {id,path:item.path,restorable:true};}
  async restore(payload){const item=this.store.state.trash.find(t=>t.id===payload.id);if(!item)throw new Error('The retained item does not exist.');if(item.root!==this.root())throw new Error('Open the original workspace before restoring this item.');const destination=this.resolve(item.path);if(fs.existsSync(destination))throw new Error('Restore cannot replace an existing file or folder.');if(!fs.existsSync(item.retained))throw new Error('The retained item is unavailable.');await fsp.mkdir(path.dirname(destination),{recursive:true});await fsp.cp(item.retained,destination,{recursive:true,force:false,errorOnExist:true});await fsp.rm(item.retained,{recursive:true});this.store.state.trash=this.store.state.trash.filter(t=>t.id!==item.id);this.store.save();this.changed(item.path);return {path:item.path};}
  changed(relative){this.emit({type:'workspace:changed',root:this.root(),path:relative});}
  async files(){const result=[];let examined=0;const walk=async(directory)=>{for(const entry of await fsp.readdir(directory,{withFileTypes:true})){if(++examined>20000)return;if(EXCLUDED.has(entry.name)||entry.isSymbolicLink())continue;const target=path.join(directory,entry.name);if(entry.isDirectory())await walk(target);else if(entry.isFile()&&(await fsp.stat(target)).size<=MAX_FILE)result.push(this.rel(target));if(result.length>=4000)return;}};await walk(this.root());return result;}
  async search(payload={}){if(typeof payload.query!=='string'||!payload.query||payload.query.length>300)throw new Error('Enter a search query of 1–300 characters.');if(payload.regex)throw new Error('Workspace regular expressions are disabled to prevent unbounded searches. Use literal text.');const matches=[];let scannedBytes=0,truncated=false;const needle=payload.caseSensitive?payload.query:payload.query.toLowerCase();for(const filename of await this.files()){const bytes=await fsp.readFile(this.resolve(filename));scannedBytes+=bytes.length;if(scannedBytes>32*1024*1024){truncated=true;break;}if(bytes.includes(0))continue;const lines=bytes.toString('utf8').split(/\r?\n/);for(let index=0;index<lines.length;index++){const text=lines[index];const haystack=payload.caseSensitive?text:text.toLowerCase();let offset=0,column;while((column=haystack.indexOf(needle,offset))!==-1){matches.push({path:filename,line:index+1,column:column+1,text:text.slice(0,1000)});offset=column+Math.max(1,needle.length);if(matches.length>=1000){truncated=true;break;}}if(truncated)break;}if(truncated)break;}return {matches,truncated,scannedBytes};}
  async replace(payload={}){if(typeof payload.query!=='string'||!payload.query||typeof payload.replacement!=='string')throw new Error('Search and replacement text are required.');if(!Array.isArray(payload.paths)||payload.paths.length>50)throw new Error('Select at most 50 explicit files.');const changes=[];for(const filename of [...new Set(payload.paths)]){const file=await this.read({path:filename});const expected=payload.revisions?.[filename];if(!expected||expected!==file.revision)throw new Error(`${filename} changed. Preview replacements again.`);const content=file.content.split(payload.query).join(payload.replacement);if(Buffer.byteLength(content)>MAX_FILE)throw new Error('Replacement exceeds the file size limit.');if(content!==file.content)changes.push({path:filename,before:file.content,after:content,revision:file.revision,count:file.content.split(payload.query).length-1});}if(!payload.confirmed)return {preview:true,changes};for(const change of changes)await this.save({path:change.path,content:change.after,revision:change.revision});this.store.receipt('workspace:replace','completed',{files:changes.map(c=>c.path),count:changes.reduce((s,c)=>s+c.count,0)});return {applied:true,count:changes.length};}
  close(){this.watcher?.close();}
}
module.exports={Workspace,revision,language,contained,MAX_FILE};
